apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  # namespace: rocketchat
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@nitamowj.ir
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
