apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmongo
  namespace: rocketchat
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /etc/mongo/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmongo
  namespace: rocketchat
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce 
  volumeName: rocketmongo
  resources:
    requests:
      storage: 1Gi