apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jitsi-web
  namespace: rocketchat
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/server-snippet: |
      location / {
      proxy_set_header Upgrade $http_upgrade;
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header Connection "upgrade";
      proxy_cache_bypass $http_upgrade;
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jitsi.nitamowj.ir
      secretName: nita-jitsi-tls
  rules:
    - host: jitsi.nitamowj.ir
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: jitsi-web
                port:
                  name: http