apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketjitsi
  namespace: rocketchat
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /etc/jitsi/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jitsi-conf
  namespace: rocketchat
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce 
  volumeName: rocketjitsi
  resources:
    requests:
      storage: 1Gi